# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: component.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='component.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63omponent.proto\"\xf2\x03\n\x0cpredictInput\x12\n\n\x02id\x18\x01 \x03(\x01\x12\x1d\n\x15overall_Xstar_Xrating\x18\x02 \x03(\x01\x12\x14\n\x0cprice_Xrange\x18\x03 \x03(\t\x12&\n\x1erestaurant_Xservices_Xdelivery\x18\x04 \x03(\x05\x12&\n\x1erestaurant_Xservices_Xcatering\x18\x05 \x03(\x05\x12$\n\x1crestaurant_Xservices_Xgroups\x18\x06 \x03(\x05\x12\"\n\x1arestaurant_Xservices_Xkids\x18\x07 \x03(\x05\x12%\n\x1drestaurant_Xservices_Xoutdoor\x18\x08 \x03(\x05\x12%\n\x1drestaurant_Xservices_Xreserve\x18\t \x03(\x05\x12%\n\x1drestaurant_Xservices_Xtakeout\x18\n \x03(\x05\x12$\n\x1crestaurant_Xservices_Xwaiter\x18\x0b \x03(\x05\x12%\n\x1drestaurant_Xservices_Xwalkins\x18\x0c \x03(\x05\x12\x14\n\x0cparking_Xlot\x18\r \x03(\x05\x12\x17\n\x0fparking_Xstreet\x18\x0e \x03(\x05\x12\x16\n\x0eparking_Xvalet\x18\x0f \x03(\x05\"\x1a\n\rpredictOutput\x12\t\n\x01x\x18\x01 \x03(\t2;\n\x0fpredict_service\x12(\n\x07predict\x12\r.predictInput\x1a\x0e.predictOutput')
)




_PREDICTINPUT = _descriptor.Descriptor(
  name='predictInput',
  full_name='predictInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='predictInput.id', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='overall_Xstar_Xrating', full_name='predictInput.overall_Xstar_Xrating', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_Xrange', full_name='predictInput.price_Xrange', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xdelivery', full_name='predictInput.restaurant_Xservices_Xdelivery', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xcatering', full_name='predictInput.restaurant_Xservices_Xcatering', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xgroups', full_name='predictInput.restaurant_Xservices_Xgroups', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xkids', full_name='predictInput.restaurant_Xservices_Xkids', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xoutdoor', full_name='predictInput.restaurant_Xservices_Xoutdoor', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xreserve', full_name='predictInput.restaurant_Xservices_Xreserve', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xtakeout', full_name='predictInput.restaurant_Xservices_Xtakeout', index=9,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xwaiter', full_name='predictInput.restaurant_Xservices_Xwaiter', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restaurant_Xservices_Xwalkins', full_name='predictInput.restaurant_Xservices_Xwalkins', index=11,
      number=12, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parking_Xlot', full_name='predictInput.parking_Xlot', index=12,
      number=13, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parking_Xstreet', full_name='predictInput.parking_Xstreet', index=13,
      number=14, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parking_Xvalet', full_name='predictInput.parking_Xvalet', index=14,
      number=15, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=518,
)


_PREDICTOUTPUT = _descriptor.Descriptor(
  name='predictOutput',
  full_name='predictOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='predictOutput.x', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=546,
)

DESCRIPTOR.message_types_by_name['predictInput'] = _PREDICTINPUT
DESCRIPTOR.message_types_by_name['predictOutput'] = _PREDICTOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

predictInput = _reflection.GeneratedProtocolMessageType('predictInput', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTINPUT,
  __module__ = 'component_pb2'
  # @@protoc_insertion_point(class_scope:predictInput)
  ))
_sym_db.RegisterMessage(predictInput)

predictOutput = _reflection.GeneratedProtocolMessageType('predictOutput', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTOUTPUT,
  __module__ = 'component_pb2'
  # @@protoc_insertion_point(class_scope:predictOutput)
  ))
_sym_db.RegisterMessage(predictOutput)



_PREDICT_SERVICE = _descriptor.ServiceDescriptor(
  name='predict_service',
  full_name='predict_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=548,
  serialized_end=607,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='predict_service.predict',
    index=0,
    containing_service=None,
    input_type=_PREDICTINPUT,
    output_type=_PREDICTOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICT_SERVICE)

DESCRIPTOR.services_by_name['predict_service'] = _PREDICT_SERVICE

# @@protoc_insertion_point(module_scope)
